# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml



pool:
  vmImage: windows-latest

steps:
- task: DownloadPipelineArtifact@2
  inputs:
    buildType: 'specific'
    project: '6fe6ea12-241d-496e-b844-5d481b3c3694'
    definition: '7'
    buildVersionToDownload: 'latest'
    artifactName: 'artifact2'
    targetPath: '$(Pipeline.Workspace)'
- task: CmdLine@2
  inputs:
    script: 'npx cypress run'    
